name: com.andromda.BetterBlockBreaking.BetterBlockBreaking
main: com.andromda.BetterBlockBreaking.BetterBlockBreaking
version: 6.6.0
api-version: 1.16
depend: [ProtocolLib]
softdepend: [WorldGuard, Towny, Slimefun]
